---
output: pdf_document
---
```{r packages}
library(readr)
full <- read_csv("diagnosing_AD_data.csv")
library(dplyr) #needed for the %>% function in the data subset loops
library(ggplot2)
library(knitr)
library(kableExtra)
```

```{r accessible subset}
a=1
b=6
c=15
access <- data.frame(matrix(nrow=174))

for (i in 1:25) {
  access <- access %>%
    mutate(full[a:(a+2)], full[b:(b+1)], full[c:(c+1)])
  
  a <- a+18
  b <- b+18
  c <- c+18
  
}

access <- access %>%
  mutate(full[451:452])

access <- subset(access, select = -(matrix.nrow...174.))
```

```{r task subsets}
d <- 2

for (i in (1:25)) {
  df <- data.frame(access[1], access[d:(d+6)])
  df <- df %>%
    mutate(access[177])
  
  assign( paste("Task", i, sep = "_"), df)
  d <- d+7
}

```

```{r demographics}
demographics <- data_frame("Class" = c("Patients", "Control Group"), "Age" = c(71.5, 68.9), "Education" = c(10.8, 12.9), "#Women" = c(46,51), "#Men" = c(44,39))
```

```{r}
Logistic <- data.frame(" " = c("Accuracy", "Sensitiviy", "Specificity"), "Original Results" = c("73.71 (+/- 6.85)", 68.06, 79.71), "Our Results" = c(70.37, 52.63, 69.23))
SVM <- data.frame(" " = c("Accuracy", "Sensitiviy", "Specificity"), "Original Results" = c("79.00 (+/- 7.55)", 77.50, 80.59), "Our Results" = c("82.06 (+/- 16.75)", 80.00, 84.12))
RF <- data.frame(" " = c("Accuracy", "Sensitiviy", "Specificity"), "Original Results" = c("88.39 (+/- 4.90)", 90.28, 86.18), "Our Results" = c("88.40 (+/- 11.77)", 94.44 ,82.35))
KNN <- data.frame(" " = c("Accuracy", "Sensitiviy", "Specificity"), "Original Results" = c("71.43 (+/- 8.34)", 89.41, 54.44), "Our Results" = c("64.75 (+/- 8.55)", 53.52, 76.47))

P_change <- data.frame(" " = c("Accuracy", "Sensitiviy", "Specificity"), "LR*" = c(-3.34, -10.48, -15.43), "SVM" = c("+3.06", "+2.50", "+3.53"), "KNN" = c(-6.68, -35.89, "+22.00"), "RF" = c(-3.83, "+4.16", "+0.01"))

Logistic %>%
  kable(col.names = c(" ", "Original Results", "Our Results"), align = 'c')
SVM %>%
  kable(col.names = c(" ", "Original Results", "Our Results"), align = 'c') 
RF %>%
  kable(col.names = c(" ", "Original Results", "Our Results"), align = 'c')
KNN %>%
  kable(col.names = c(" ", "Original Results", "Our Results"), align = 'c')
P_change %>%
  kable(col.names = c(" ", "LR*", "SVM", "KNN", "RF"), align = 'c')
```

